-- 코드를 입력하세요
SELECT a.BOOK_ID as BOOK_ID
,b.AUTHOR_NAME as AUTHOR_NAME
,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK a, AUTHOR  b

WHERE a.AUTHOR_ID=b.AUTHOR_ID and CATEGORY='경제'
ORDER BY PUBLISHED_DATE asc